### ISSUE TITLE
[PE-D][Tester D] Invalid Phone number can still be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T12-3/tp#118]
Assuming in terms of singapore context, each phone number can only have exactly 8 digits, but when I keyed in 7 digits it worked. I put low severity since this problem can be easily rectified
![Screenshot 2023-03-31 at 2.17.59 PM.png](https://raw.githubusercontent.com/sembcorpp/ped/main/files/f560b1a5-b1c1-41fc-9638-c812eef6bf8b.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: sembcorpp/ped#1

**Comment by Jarrett0203** [comment]
Can confirm that it is a bug.

**Comment by Jarrett0203** [comment]
Change validation to 8 digits starting with 6, 8 and 9.

**Comment by glyfy** [comment]
Maybe we should also update in the UG that our product is targeted towards Singaporeans ( if we are going to limit the phone number like such )
