### ISSUE TITLE
[PE-D][Tester A] No Way to show how many books has been borrowed 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T12-3/tp#120]
As a management application, it is essential to consider the accurate tracking of borrowed books and the total inventory, as this functionality is crucial to ensure the app's effectiveness and utility.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: SPWwj/ped#3

**Comment by Jarrett0203** [comment]
Valid feature flaw but won't fix.
