### ISSUE TITLE
[PE-D][Tester E] addBook does not accept large book names

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T12-3/tp#123]
## Details
- Adding large book names throws an invalid exception that "Name should only contain alphanumeric characters and spaces".
- It is unclear whether this refers to the book name or author's name.
- The User Guide also does not specify any limit on the length of bookname

## To reproduce
1. Launch the ExpressLibrary App
2. Use the `addBook` command with the following book name and author

```
addBook t/No Matter How Much You Promise to Cook or Pay the Rent You Blew It Cauze Bill Bailey Ain’t Never Coming Home Again a/Edgardo Vega Yunque i/9780312424022
```

## Expected behavior
- Book gets added to the ExpressLibrary

## Screenshots

![bookBug.png](https://raw.githubusercontent.com/vigonometry/ped/main/files/e83ea5f7-a37c-464b-87c1-d81f9bc2e2d1.png)

## System Details
Desktop
OS: Mac OS Ventura 13.1
JDK: OpenJDK 11/Azul Build
Resolution: 1920 x 1080
Version: v1.3

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: vigonometry/ped#2

**Comment by Jarrett0203** [comment]
Bug exists.

**Comment by Jarrett0203** [comment]
Change person name and author name as well

**Comment by sanjevi13** [comment]
I feel that the MESSAGE_CONSTRAINTS are slightly unnecessary after these changes are made for person, author and title because of the way regex works. Still did it anyway.
