### ISSUE TITLE
[PE-D][Tester B] EditBook feature unable to find book

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T12-3/tp#133]
![image.png](https://raw.githubusercontent.com/jamieeeleow/ped/main/files/89fc3cb1-1c86-4b68-b905-4b2a1582393c.png)

Despite having 11 books available in the booklist, it is stated that nothing was found.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: jamieeeleow/ped#4

**Comment by Jarrett0203** [comment]
Cause of this is in #140.
